[package]
name = "spin-sdk"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = "1.64"

[lib]
name = "spin_sdk"

[dependencies]
anyhow = "1"
async-trait = "0.1.74"
form_urlencoded = "1.0"
spin-macro = { path = "macro" }
thiserror = "1.0.37"
# Use a sha commit for now to include https://github.com/bytecodealliance/wit-bindgen/pull/693
# Once wit-bindgen 0.13 is released we can move to that version.
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "2405a79c74c5d61b9bc88c378d475c6c21ed6a9f" }
routefinder = "0.5.3"
once_cell = "1.18.0"
futures = "0.3.28"
serde_json = { version = "1.0.96", optional = true }
serde = { version = "1.0.163", optional = true }
http_types = { package = "http", version = "0.2", optional = true }
bytes = { version = "1", optional = true }

[features]
default = ["export-sdk-language", "http", "json"]
http = ["dep:http_types", "dep:bytes"]
export-sdk-language = []
json = ["dep:serde", "dep:serde_json"]
experimental = []
