[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
http = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
spin-sdk = { path = "../.." }
